name: Build, Test, and Push Docker Image

on:
  push:
    branches:
      - main  # Trigger workflow on push to the main branch
  pull_request:
    branches:
      - main  # Also trigger on pull requests

jobs:
  build-test-and-push:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python environment
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Run tests using unittest
    - name: Run unittest
      run: |
        python -m unittest discover tests

    # Step 5: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 6: Build the Docker image
    - name: Build Docker image
      run: |
        IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/tictactoe_gui"
        TAG="${{ github.sha }}"
        docker build -t $IMAGE_NAME:latest -t $IMAGE_NAME:$TAG .

    # Step 7: Push the Docker image
    - name: Push Docker image
      run: |
        IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/tictactoe_gui"
        TAG="${{ github.sha }}"
        docker push $IMAGE_NAME:latest
        docker push $IMAGE_NAME:$TAG
